### ISSUE TITLE
Can the MV-diffusion model inference in different view_num and image_size?

### ISSUE THREAD

**Issue by w2690831985w** [zju3dv/Coin3D#5]
First, thanks for your great work!

I have some questions about the pre-trained model.

In `ctrldemo.yaml`:

```
model:
  base_learning_rate: 5.0e-05
  target: ldm.models.diffusion.ctrldemo_sync_dreamer.CtrlDemo
  params:
    view_num: 16
    image_size: 256
...
```

I changed view_num to 32, but errors occurred. I wonder if the model uses fixed view_num and image_size?

Errors:
```
RuntimeError: Error(s) in loading state_dict for CtrlDemo:
        size mismatch for poses: copying a param with shape torch.Size([16, 3, 4]) from checkpoint, the shape in current model is torch.Size([32, 4, 4]).
        size mismatch for Ks: copying a param with shape torch.Size([16, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 3, 3]).
        size mismatch for azimuth: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).
        size mismatch for spatial_volume.spatial_volume_feats.init_conv.weight: copying a param with shape torch.Size([64, 256, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 512, 3, 3, 3]).
        size mismatch for spatial_volume.controlnet.init_conv.weight: copying a param with shape torch.Size([64, 256, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 512, 3, 3, 3]).
```
